import { Document, Packer, Paragraph, TextRun, AlignmentType, HeadingLevel, BorderStyle } from 'docx';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

const WATERMARK_TEXT = "Generated by CVGenie - Upgrade to Pro to remove watermark";

interface ExportOptions {
  isPro?: boolean;
  documentType?: 'resume' | 'coverLetter';
}

export async function generatePDFFromText(content: string, options: ExportOptions = {}): Promise<Buffer> {
  const { isPro = false } = options;
  
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  
  const lines = content.split('\n');
  const pageWidth = 612;
  const pageHeight = 792;
  const margin = 50;
  const lineHeight = 14;
  const maxWidth = pageWidth - (margin * 2);
  
  let page = pdfDoc.addPage([pageWidth, pageHeight]);
  let yPosition = pageHeight - margin;
  
  const addWatermark = (page: any) => {
    if (!isPro) {
      page.drawText(WATERMARK_TEXT, {
        x: margin,
        y: 20,
        size: 8,
        font: font,
        color: rgb(0.6, 0.6, 0.6),
      });
    }
  };
  
  addWatermark(page);
  
  const wrapText = (text: string, fontSize: number): string[] => {
    const words = text.split(' ');
    const lines: string[] = [];
    let currentLine = '';
    
    for (const word of words) {
      const testLine = currentLine ? `${currentLine} ${word}` : word;
      const textWidth = font.widthOfTextAtSize(testLine, fontSize);
      
      if (textWidth > maxWidth && currentLine) {
        lines.push(currentLine);
        currentLine = word;
      } else {
        currentLine = testLine;
      }
    }
    
    if (currentLine) {
      lines.push(currentLine);
    }
    
    return lines;
  };
  
  for (const line of lines) {
    const trimmedLine = line.trim();
    
    if (yPosition < margin + 30) {
      page = pdfDoc.addPage([pageWidth, pageHeight]);
      yPosition = pageHeight - margin;
      addWatermark(page);
    }
    
    const isHeader = trimmedLine.match(/^[A-Z][A-Z\s]+$/) || 
                     trimmedLine.match(/^(PROFESSIONAL SUMMARY|EXPERIENCE|EDUCATION|SKILLS|CONTACT|OBJECTIVE)/i);
    const isBullet = trimmedLine.startsWith('•') || trimmedLine.startsWith('-') || trimmedLine.startsWith('*');
    
    let fontSize = 11;
    let selectedFont = font;
    let xOffset = margin;
    
    if (isHeader) {
      fontSize = 13;
      selectedFont = boldFont;
      yPosition -= 8;
    } else if (isBullet) {
      xOffset = margin + 15;
    }
    
    if (trimmedLine === '') {
      yPosition -= lineHeight / 2;
      continue;
    }
    
    const wrappedLines = wrapText(trimmedLine, fontSize);
    
    for (const wrappedLine of wrappedLines) {
      if (yPosition < margin + 30) {
        page = pdfDoc.addPage([pageWidth, pageHeight]);
        yPosition = pageHeight - margin;
        addWatermark(page);
      }
      
      page.drawText(wrappedLine, {
        x: xOffset,
        y: yPosition,
        size: fontSize,
        font: selectedFont,
        color: rgb(0, 0, 0),
      });
      
      yPosition -= lineHeight;
    }
    
    if (isHeader) {
      yPosition -= 4;
    }
  }
  
  const pdfBytes = await pdfDoc.save();
  return Buffer.from(pdfBytes);
}

export async function generateDOCXFromText(content: string, options: ExportOptions = {}): Promise<Buffer> {
  const { isPro = false } = options;
  
  const lines = content.split('\n');
  const paragraphs: Paragraph[] = [];
  
  if (!isPro) {
    paragraphs.push(
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({
            text: WATERMARK_TEXT,
            size: 16,
            color: "999999",
            italics: true,
          }),
        ],
        spacing: { after: 200 },
      })
    );
  }
  
  for (const line of lines) {
    const trimmedLine = line.trim();
    
    const isHeader = trimmedLine.match(/^[A-Z][A-Z\s]+$/) || 
                     trimmedLine.match(/^(PROFESSIONAL SUMMARY|EXPERIENCE|EDUCATION|SKILLS|CONTACT|OBJECTIVE)/i);
    const isBullet = trimmedLine.startsWith('•') || trimmedLine.startsWith('-') || trimmedLine.startsWith('*');
    
    if (trimmedLine === '') {
      paragraphs.push(new Paragraph({ spacing: { after: 100 } }));
      continue;
    }
    
    if (isHeader) {
      paragraphs.push(
        new Paragraph({
          children: [
            new TextRun({
              text: trimmedLine,
              bold: true,
              size: 26,
              color: "2B579A",
            }),
          ],
          spacing: { before: 200, after: 100 },
          border: {
            bottom: {
              color: "2B579A",
              space: 1,
              size: 6,
              style: BorderStyle.SINGLE,
            },
          },
        })
      );
    } else if (isBullet) {
      const bulletText = trimmedLine.replace(/^[•\-\*]\s*/, '');
      paragraphs.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `• ${bulletText}`,
              size: 22,
            }),
          ],
          indent: { left: 360 },
          spacing: { after: 60 },
        })
      );
    } else {
      paragraphs.push(
        new Paragraph({
          children: [
            new TextRun({
              text: trimmedLine,
              size: 22,
            }),
          ],
          spacing: { after: 60 },
        })
      );
    }
  }
  
  if (!isPro) {
    paragraphs.push(
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({
            text: WATERMARK_TEXT,
            size: 16,
            color: "999999",
            italics: true,
          }),
        ],
        spacing: { before: 400 },
      })
    );
  }
  
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: paragraphs,
      },
    ],
  });
  
  const buffer = await Packer.toBuffer(doc);
  return buffer;
}

export function generateTXTFromText(content: string, options: ExportOptions = {}): Buffer {
  const { isPro = false } = options;
  
  let output = content;
  
  if (!isPro) {
    output = `${WATERMARK_TEXT}\n${'='.repeat(60)}\n\n${content}\n\n${'='.repeat(60)}\n${WATERMARK_TEXT}`;
  }
  
  return Buffer.from(output, 'utf-8');
}

export interface ResumeData {
  personalInfo: {
    name: string;
    email: string;
    phone: string;
    location: string;
  };
  summary: string;
  experience: Array<{
    title: string;
    company: string;
    duration: string;
    description: string;
  }>;
  education: Array<{
    degree: string;
    institution: string;
    year: string;
  }>;
  skills: string[];
}

const documentGenerator = {
  generatePDFFromText,
  generateDOCXFromText,
  generateTXTFromText,
};

export default documentGenerator;
