// PDF imports removed
import officegen from 'officegen';
import fs from 'fs';
import path from 'path';
import { promisify } from 'util';
import { Document, Packer, Paragraph, TextRun, AlignmentType, HeadingLevel } from 'docx';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

const mkdir = promisify(fs.mkdir);

interface ResumeData {
  personalInfo: {
    name: string;
    email: string;
    phone: string;
    location: string;
  };
  summary: string;
  experience: Array<{
    title: string;
    company: string;
    duration: string;
    description: string;
  }>;
  education: Array<{
    degree: string;
    institution: string;
    year: string;
  }>;
  skills: string[];
}

// Watermark configuration
const WATERMARK_CONFIG = {
  text: "Generated by CVGenie – Upgrade to Pro to remove watermark",
  fontSize: 10,
  color: { r: 0.7, g: 0.7, b: 0.7 },
  opacity: 0.5
};

class DocumentGenerator {
  private async ensureTempDir(): Promise<string> {
    const tempDir = path.join(process.cwd(), 'tmp');
    try {
      await mkdir(tempDir, { recursive: true });
    } catch (error) {
      // Directory already exists
    }
    return tempDir;
  }

  // generatePDF function removed as requested

  async generateDOCX(resumeData: ResumeData, content: string, isPro: boolean = false): Promise<Buffer> {
    const watermarkParagraph = !isPro ? new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: WATERMARK_CONFIG.text,
          size: 16,
          color: "AAAAAA",
          italics: true,
        }),
      ],
    }) : null;

    const docx = officegen('docx');

    const sections = [
      {
        properties: {},
        children: [
          // Watermark for Free users (at top)
          ...(watermarkParagraph ? [watermarkParagraph] : []),

          // Header
          new Paragraph({
            text: resumeData.personalInfo.name,
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            text: resumeData.personalInfo.email,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            text: resumeData.personalInfo.phone,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            text: resumeData.personalInfo.location,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({}), // Spacer
        ],
      },
      // Summary Section
      {
        properties: {},
        children: [
          new Paragraph({
            text: 'Professional Summary',
            heading: HeadingLevel.HEADING_2,
          }),
          new Paragraph({
            text: resumeData.summary,
          }),
          new Paragraph({}), // Spacer
        ],
      },
    ];

    // Experience Section
    if (resumeData.experience && resumeData.experience.length > 0) {
      sections.push({
        properties: {},
        children: [
          new Paragraph({
            text: 'Experience',
            heading: HeadingLevel.HEADING_2,
          }),
          ...resumeData.experience.flatMap(exp => [
            new Paragraph({
              children: [
                new TextRun({ text: exp.title, bold: true }),
                new TextRun({ text: ` at ${exp.company}` }),
              ],
            }),
            new Paragraph({ text: exp.duration }),
            new Paragraph({ text: exp.description }),
            new Paragraph({}), // Spacer
          ]),
        ],
      });
    }

    // Education Section
    if (resumeData.education && resumeData.education.length > 0) {
      sections.push({
        properties: {},
        children: [
          new Paragraph({
            text: 'Education',
            heading: HeadingLevel.HEADING_2,
          }),
          ...resumeData.education.flatMap(edu => [
            new Paragraph({ text: `${edu.degree} - ${edu.institution}` }),
            new Paragraph({ text: edu.year }),
            new Paragraph({}), // Spacer
          ]),
        ],
      });
    }

    // Skills Section
    if (resumeData.skills && resumeData.skills.length > 0) {
      sections.push({
        properties: {},
        children: [
          new Paragraph({
            text: 'Skills',
            heading: HeadingLevel.HEADING_2,
          }),
          new Paragraph({
            text: resumeData.skills.join(', '),
          }),
        ],
      });
    }

    docx.createSection({ headers: { default: { sections: sections } } });

    return new Promise((resolve, reject) => {
      try {
        const out = fs.createWriteStream(outputPath);

        out.on('error', reject);
        out.on('close', () => resolve(outputPath));

        docx.generate(out);
      } catch (error) {
        reject(error);
      }
    });
  }


  async generateMultipleFormats(
    resumeContent: string, 
    coverLetterContent: string, 
    baseFilename: string,
    formats: string[] = ['docx'],
    isPro: boolean = false // Default to free user
  ): Promise<ExportFiles> {
    const tempDir = await this.ensureTempDir();
    const outputs: ExportFiles = {};

    try {
      // PDF generation removed as requested

      if (formats.includes('docx')) {
        outputs.resumeDOCX = await this.generateDOCX(
          JSON.parse(resumeContent), 
          path.join(tempDir, `${baseFilename}_resume.docx`),
          isPro
        );
        outputs.coverLetterDOCX = await this.generateDOCX(
          JSON.parse(coverLetterContent), 
          path.join(tempDir, `${baseFilename}_cover_letter.docx`),
          isPro
        );
      }

      return outputs;
    } catch (error) {
      throw new Error(`Failed to generate documents: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }
}

export default new DocumentGenerator();

// Helper functions for PDF generation (moved from DocumentGenerator class)
export async function generatePDF(resumeData: ResumeData, content: string, isPro: boolean = false): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  let page = pdfDoc.addPage();
  const { width, height } = page.getSize();
  let yPosition = height - 50;

  const drawText = (text: string, size: number, isBold = false) => {
    const selectedFont = isBold ? boldFont : font;
    if (yPosition < 50) {
      page = pdfDoc.addPage();
      yPosition = height - 50;

      // Add watermark to new page for Free users
      if (!isPro) {
        addWatermarkToPDFPage(page, font, width, height);
      }
    }
    page.drawText(text, {
      x: 50,
      y: yPosition,
      size,
      font: selectedFont,
      color: rgb(0, 0, 0),
    });
    yPosition -= size + 10;
  };

  // Helper function to add watermark to a PDF page
  const addWatermarkToPDFPage = (page: any, font: any, width: number, height: number) => {
    const watermarkText = WATERMARK_CONFIG.text;
    const watermarkSize = WATERMARK_CONFIG.fontSize;

    // Draw watermark diagonally across the page
    page.drawText(watermarkText, {
      x: width / 2 - 150,
      y: height / 2,
      size: watermarkSize,
      font: font,
      color: rgb(WATERMARK_CONFIG.color.r, WATERMARK_CONFIG.color.g, WATERMARK_CONFIG.color.b),
      opacity: WATERMARK_CONFIG.opacity,
      rotate: { angle: -45, type: 1 }
    });
  };

  // Add watermark to first page for Free users
  if (!isPro) {
    page.drawText(WATERMARK_CONFIG.text, {
      x: width / 2 - 150,
      y: height / 2,
      size: WATERMARK_CONFIG.fontSize,
      font: font,
      color: rgb(WATERMARK_CONFIG.color.r, WATERMARK_CONFIG.color.g, WATERMARK_CONFIG.color.b),
      opacity: WATERMARK_CONFIG.opacity,
      rotate: { angle: -45, type: 1 }
    });
  }

  // Draw content
  drawText(resumeData.personalInfo.name, 20, true);
  drawText(resumeData.personalInfo.email, 12);
  drawText(resumeData.personalInfo.phone, 12);
  drawText(resumeData.personalInfo.location, 12);
  yPosition -= 10;

  drawText('Professional Summary', 16, true);
  drawText(resumeData.summary, 12);
  yPosition -= 10;

  if (resumeData.experience && resumeData.experience.length > 0) {
    drawText('Experience', 16, true);
    resumeData.experience.forEach(exp => {
      drawText(`${exp.title} at ${exp.company}`, 14, true);
      drawText(exp.duration, 12);
      drawText(exp.description, 12);
      yPosition -= 5;
    });
    yPosition -= 10;
  }

  if (resumeData.education && resumeData.education.length > 0) {
    drawText('Education', 16, true);
    resumeData.education.forEach(edu => {
      drawText(`${edu.degree} - ${edu.institution}`, 12);
      drawText(edu.year, 12);
      yPosition -= 5;
    });
    yPosition -= 10;
  }

  if (resumeData.skills && resumeData.skills.length > 0) {
    drawText('Skills', 16, true);
    drawText(resumeData.skills.join(', '), 12);
  }

  const pdfBytes = await pdfDoc.save();
  return Buffer.from(pdfBytes);
}